"""PRISMA — Streamlit demo home page."""
from __future__ import annotations

from pathlib import Path

import streamlit as st

from prisma import __version__

REPO_ROOT = Path(__file__).resolve().parent.parent

st.set_page_config(
    page_title="PRISMA — research transparency toolkit by Proportione",
    page_icon="🔬",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown(
    """
    <style>
      .pp-title { color: #5F322F; font-weight: 700; }
      .pp-pill {
        display: inline-block; padding: 2px 10px; border-radius: 12px;
        background: #F5F1EE; color: #5F322F; font-size: 0.85rem; margin-right: 6px;
      }
      .pp-card {
        border: 1px solid #E5DCD7; border-radius: 8px; padding: 16px 20px;
        background: #FFFFFF; height: 100%;
      }
    </style>
    """,
    unsafe_allow_html=True,
)

st.markdown('<h1 class="pp-title">PRISMA</h1>', unsafe_allow_html=True)
st.markdown(
    f"<span class='pp-pill'>v{__version__}</span>"
    "<span class='pp-pill'>by Proportione</span>"
    "<span class='pp-pill'>MIT licence</span>",
    unsafe_allow_html=True,
)

st.write(
    "A Python toolkit for systematic literature reviews — corpus ingestion, "
    "two-tier screening, full-text extraction, MMAT 2018 quality assessment, "
    "PRISMA 2020 reporting, and bibliometric clustering. "
    "Released as open source so reviewers can audit the methodology and other "
    "researchers can reuse the pipeline."
)

st.divider()

st.subheader("Pipeline at a glance")
cols = st.columns(4)
items = [
    ("Screening", "1_Screening", "Two-tier rule engine. Hard exclusions then multi-group inclusion. Every decision traceable."),
    ("Extraction", "2_Extraction", "PyMuPDF text + taxonomy-driven field extraction from full-text PDFs."),
    ("Quality (MMAT 2018)", "3_Quality_MMAT", "Hong et al. 2018 quantitative-descriptive heuristic scoring (Q1–Q5)."),
    ("Bibliometrics", "4_Bibliometrics", "VOSviewer .net loader · Louvain communities · co-occurrence."),
]
for col, (label, slug, desc) in zip(cols, items, strict=False):
    with col:
        st.markdown(
            f"""
            <div class='pp-card'>
              <div style='color:#5F322F;font-weight:600;font-size:1.05rem;'>{label}</div>
              <div style='color:#1F1410;margin-top:6px;font-size:0.93rem;'>{desc}</div>
            </div>
            """,
            unsafe_allow_html=True,
        )

st.divider()

left, right = st.columns([3, 2])
with left:
    st.subheader("Reference PRISMA 2020 flow")
    flow_png = REPO_ROOT / "reports" / "demo-prisma-flow.png"
    if flow_png.exists():
        st.image(str(flow_png), caption="Generated by `prisma report` from a JSON counts file.")
    else:
        st.info(
            "Run `prisma report --counts examples/prisma_counts_demo.json "
            "--out reports/demo-prisma-flow.png` to generate the demo flow."
        )

with right:
    st.subheader("Methodology")
    st.markdown(
        "- **PRISMA 2020** — Page et al. (2021). *BMJ* 372:n71.\n"
        "- **MMAT 2018** — Hong et al. (2018). *Education for Information* 34:285-291.\n"
        "- **Case Survey** — Larsson (1993). *Academy of Management Journal* 36(6).\n"
        "- **Bibliometrics** — Donthu et al. (2021). *Journal of Business Research* 133.\n"
    )
    st.subheader("Disclaimer")
    st.caption(
        "This toolkit helps authors comply with PRISMA 2020 reporting. "
        "It is not affiliated with or endorsed by the PRISMA Statement Group "
        "or the EQUATOR Network."
    )

st.divider()
st.markdown(
    "**Research at Proportione** → "
    "[proportione.com/investigacion](https://proportione.com/investigacion) · "
    "**Source** → [github.com/Proportione/PRISMA](https://github.com/Proportione/PRISMA)"
)
